#!/usr/bin/env python3
"""
Script to add automatic labels and explanations to a v2 CMDI tweak file,
merging existing explanations from a v1 tweak file via a column mapping CSV.

Automatically generated by Claude AI, Opus 4.6. The output was manually inspected for correctness.

For each Component or Element under DataEnvelope (starting from DataEnvelopeMetadata):
  1. Adds: <clariah:label xml:lang="en">Level n: Spaced Name</clariah:label>
  2. Adds: <clariah:explanation>...</clariah:explanation> where:
     - If v1 had an explanation: "V1 explanation text. See documentation at: URL#Spaced-Name"
     - If v1 had no explanation: "See documentation at: URL#Spaced-Name"
"""

import re
import csv
from lxml import etree

# ============================================================
# CONFIGURATION — edit these paths to match your environment
# ============================================================
V1_TWEAK_PATH = "/Users/lilianam/workspace/hi-data-envelop-editor/data/apps/data-envelopes/profiles/clarin.eu:cr1:p_1708423613607/tweaks/tweak-1.xml"
V2_TWEAK_PATH = "/Users/lilianam/workspace/hi-data-envelop-editor/data/apps/data-envelopes-v2/profiles/clarin.eu:cr1:p_1770289476181/tweaks/tweak-1.xml"
MAPPING_CSV_PATH = "/Users/lilianam/workspace/hi-data-envelop-editor/xslt/test-ai/column-mapping-v1-to-v2.csv"
OUTPUT_PATH = "/Users/lilianam/workspace/hi-data-envelop-editor/data/apps/data-envelopes/profiles/clarin.eu:cr1:p_1708423613607/tweaks/tweak-1-version2-labelled.xml"

BASE_URL = "https://edu.nl/atqm8"
START_FROM = "DataEnvelopeMetadata"  # Component name where numbering begins (Level 1)

# ============================================================
# Constants
# ============================================================
CLARIAH_NS = "http://www.clariah.eu/"


# ============================================================
# Helpers
# ============================================================
def camel_to_spaced(name):
    """Convert camelCase/PascalCase to spaced words.
    e.g. DataEnvelopeMetadata -> Data Envelope Metadata
         controlledTerm -> Controlled Term
    """
    s = re.sub(r'([a-z])([A-Z])', r'\1 \2', name)
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1 \2', s)
    s = s[0].upper() + s[1:]
    return s


def get_element_path(elem):
    """Build path from ancestor Component/Element @name values.
    e.g. /DataEnvelope/DatasetMetadata/Genre/controlledTerm
    """
    parts = []
    p = elem
    while p is not None:
        if p.tag in ("Component", "Element"):
            name = p.get("name", "")
            if name:
                parts.insert(0, name)
        p = p.getparent()
    return "/" + "/".join(parts)


def load_column_mapping(csv_path):
    """Load v1→v2 column mapping from CSV.
    Returns dict: v1_path → v2_path
    """
    mapping = {}
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            v1 = row.get("v1_column", "").strip()
            v2 = row.get("v2_column", "").strip()
            if v1 and v2:
                mapping[v1] = v2
    return mapping


def build_full_mapping(column_mapping):
    """Extend the element-level mapping with component-level mappings
    inferred by walking up the path hierarchy.
    e.g. if /A/B/C/elem → /X/Y/Z/elem2, infer /A/B/C → /X/Y/Z, /A/B → /X/Y, etc.
    """
    full = dict(column_mapping)
    for v1_path, v2_path in column_mapping.items():
        v1_parts = v1_path.split("/")
        v2_parts = v2_path.split("/")
        for i in range(1, min(len(v1_parts), len(v2_parts))):
            v1_parent = "/".join(v1_parts[:-i])
            v2_parent = "/".join(v2_parts[:-i])
            if v1_parent and v2_parent and v1_parent not in full:
                full[v1_parent] = v2_parent
    return full


def extract_v1_explanations(v1_tree, full_mapping):
    """Extract clariah:explanation texts from v1 elements/components,
    mapped to their corresponding v2 paths.
    Returns dict: v2_path → explanation text
    """
    v2_explanations = {}
    unmapped = []

    for expl in v1_tree.getroot().iter(f"{{{CLARIAH_NS}}}explanation"):
        parent = expl.getparent()
        if parent is None or parent.tag not in ("Component", "Element"):
            continue
        text = (expl.text or "").strip()
        if not text:
            continue

        v1_path = get_element_path(parent)
        v2_path = full_mapping.get(v1_path)

        if v2_path:
            if v2_path in v2_explanations:
                # Multiple v1 explanations map to same v2 path — concatenate
                v2_explanations[v2_path] += " " + text
            else:
                v2_explanations[v2_path] = text
        else:
            unmapped.append((v1_path, text))

    return v2_explanations, unmapped


# ============================================================
# Main processing
# ============================================================
def process_node(elem, counters, depth, v2_explanations):
    """Add clariah:label and clariah:explanation to a Component or Element."""
    name = elem.get("name", "")
    if not name:
        return

    # --- Build label ---
    number = ".".join(str(c) for c in counters)
    spaced_name = camel_to_spaced(name)
    label_text = f"Level {number}: {spaced_name}"

    # --- Build explanation ---
    url_name = spaced_name.replace(" ", "-")
    auto_part = f"See documentation at: {BASE_URL}#{url_name}"

    v2_path = get_element_path(elem)
    v1_text = v2_explanations.get(v2_path, "").strip()

    if v1_text:
        if not v1_text.endswith((".", "!", "?", ":")):
            v1_text += "."
        explanation_text = f"{v1_text} {auto_part}"
    else:
        explanation_text = auto_part

    # --- Create and insert elements ---
    label_elem = etree.SubElement(elem, f"{{{CLARIAH_NS}}}label")
    label_elem.set("{http://www.w3.org/XML/1998/namespace}lang", "en")
    label_elem.text = label_text
    label_elem.tail = "\n" + "\t" * (depth + 1)

    expl_elem = etree.SubElement(elem, f"{{{CLARIAH_NS}}}explanation")
    expl_elem.text = explanation_text
    expl_elem.tail = "\n" + "\t" * (depth + 1)

    # Move label and explanation to be the first children
    elem.remove(label_elem)
    elem.remove(expl_elem)
    elem.insert(0, expl_elem)
    elem.insert(0, label_elem)

    # --- Recurse into child Components and Elements ---
    child_counter = 0
    for child in list(elem):
        if child.tag in ("Component", "Element"):
            child_counter += 1
            process_node(child, counters + [child_counter], depth + 1, v2_explanations)


def main():
    # --- Load column mapping ---
    print(f"Loading column mapping: {MAPPING_CSV_PATH}")
    column_mapping = load_column_mapping(MAPPING_CSV_PATH)
    full_mapping = build_full_mapping(column_mapping)
    print(f"  Element mappings: {len(column_mapping)}")
    print(f"  Total mappings (incl. inferred components): {len(full_mapping)}")

    # --- Extract v1 explanations ---
    print(f"\nParsing v1 tweak: {V1_TWEAK_PATH}")
    v1_tree = etree.parse(V1_TWEAK_PATH)
    v2_explanations, unmapped = extract_v1_explanations(v1_tree, full_mapping)
    print(f"  V1 explanations found: {len(v2_explanations) + len(unmapped)}")
    print(f"  Mapped to v2 paths: {len(v2_explanations)}")
    if unmapped:
        print(f"  Unmapped ({len(unmapped)}):")
        for path, text in unmapped:
            print(f"    {path}: {text[:60]}")

    # --- Parse v2 tweak template ---
    print(f"\nParsing v2 tweak: {V2_TWEAK_PATH}")
    v2_tree = etree.parse(V2_TWEAK_PATH)
    v2_root = v2_tree.getroot()

    # --- Find DataEnvelope ---
    data_envelope = None
    for comp in v2_root.findall("Component"):
        if comp.get("name") == "DataEnvelope":
            data_envelope = comp
            break

    if data_envelope is None:
        print("ERROR: DataEnvelope component not found in v2")
        return

    # --- Add labels and explanations ---
    print(f"\nAdding labels (starting from {START_FROM})...")
    started = False
    top_counter = 0
    for child in list(data_envelope):
        if child.tag in ("Component", "Element"):
            if child.get("name") == START_FROM:
                started = True
            if started:
                top_counter += 1
                process_node(child, [top_counter], 2, v2_explanations)

    # --- Write output ---
    output = etree.tostring(v2_tree, xml_declaration=True, encoding="UTF-8", pretty_print=True).decode()
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"\nOutput written to: {OUTPUT_PATH}")

    # --- Verification ---
    labels = list(v2_root.iter(f"{{{CLARIAH_NS}}}label"))
    expls = list(v2_root.iter(f"{{{CLARIAH_NS}}}explanation"))
    merged = sum(1 for e in expls if e.text and "See documentation at:" in e.text and not e.text.startswith("See"))
    auto_only = sum(1 for e in expls if e.text and e.text.startswith("See documentation at:"))

    print(f"\nVerification:")
    print(f"  Labels added: {len(labels)}")
    print(f"  Explanations added: {len(expls)}")
    print(f"    With v1 text merged: {merged}")
    print(f"    Auto-generated only: {auto_only}")
    if labels:
        print(f"  First: {labels[0].text}")
        print(f"  Last:  {labels[-1].text}")

    # Confirm institute/ID/status have no labels
    print(f"\n  Skipped elements (before {START_FROM}):")
    for child in data_envelope:
        if child.tag == "Element" and child.get("name") in ("institute", "ID", "status"):
            has_label = any(c.tag == f"{{{CLARIAH_NS}}}label" for c in child)
            print(f"    {child.get('name')}: label={'YES' if has_label else 'NO'}")


if __name__ == "__main__":
    main()
